language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="6a6b0ff5-14c5-4aa7-8238-aea89ed1a3b5"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - arvikvan@gmailcom
    on_success: never # default: change
    on_failure: always # default: always